# Generated by Django 4.2.6 on 2023-11-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-timestamp', 'email']},
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Request Date'),
        ),
    ]
