# Generated by Django 4.2.6 on 2023-11-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_alter_request_options_alter_request_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.CharField(choices=[('/home/ztz/Desktop/MyProjects/2023/Pitech_company/server/media/icons/email.svg', 'Email'), ('/home/ztz/Desktop/MyProjects/2023/Pitech_company/server/media/icons/phone.svg', 'Phone'), ('/home/ztz/Desktop/MyProjects/2023/Pitech_company/server/media/icons/whatsapp.svg', 'Whatsapp'), ('/home/ztz/Desktop/MyProjects/2023/Pitech_company/server/media/icons/telegram.svg', 'Telegram')], max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram')], max_length=10),
        ),
    ]
