# Generated by Django 4.2.6 on 2023-11-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_icon_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.CharField(max_length=50),
        ),
    ]
